#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/robotics-in-concert/rocon_app_platform/license/LICENSE
#
##############################################################################

import rocon_app_utilities.create

rocon_app_utilities.create.main()
